<!--#set var="ssis.i18n.en.meta.title" value="My First SSiS Site" -->
<!--#set var="ssis.i18n.fr.meta.title" value="Mon Premier Site SSiS" -->

<!--#set var="ssis.i18n.en.meta.desc" value="My SSiS Site description" -->
<!--#set var="ssis.i18n.en.meta.desc.1-2" value="My SSiS Site description for a specific page" -->
<!--#set var="ssis.i18n.fr.meta.desc" value="Mon description du Site SSiS" -->

<!--#set var="ssis.i18n.en.header" value="Welcome to my site!" -->
<!--#set var="ssis.i18n.fr.header" value="Bienvenue a mon site!" -->
